star_wars_opinions = [
    "I absolutely loved Star Wars Episode 7! The storyline was fantastic.",
    "Star Wars Episode 7 was okay, not great but not terrible either.",
    "The new characters introduced in Episode 7 were refreshing and well-developed.",
    "I found Star Wars Episode 7 to be a bit predictable, especially for a Star Wars movie.",
    "The visual effects in Episode 7 were stunning, a true feast for the eyes.",
    "I was disappointed with the lack of originality in Star Wars Episode 7.",
    "The return of familiar faces in Episode 7 brought back a lot of nostalgia.",
    "The pacing in Star Wars Episode 7 felt a bit off at times.",
    "Rey is a strong and compelling protagonist in Episode 7.",
    "I didn't connect with the new characters introduced in Star Wars Episode 7.",
    "The humor in Episode 7 was well-executed and added a nice touch to the film.",
    "The plot twists in Star Wars Episode 7 were unexpected and kept me engaged.",
    "I didn't like how Episode 7 tried to replicate the plot of the original trilogy.",
    "The action sequences in Star Wars Episode 7 were thrilling and well-choreographed.",
    "The soundtrack for Episode 7 was iconic and added to the overall experience.",
    "Kylo Ren is a fascinating and complex villain in Star Wars Episode 7.",
    "I felt that Star Wars Episode 7 lacked the epic scale that the earlier movies had.",
    "The cinematography in Episode 7 was top-notch, capturing the essence of Star Wars.",
    "The dialogue in Star Wars Episode 7 was sometimes cheesy and forced.",
    "I appreciated the nods to the original trilogy in Episode 7.",
    "The overall tone of Star Wars Episode 7 felt too similar to other modern blockbusters.",
    "The introduction of the First Order was a compelling addition to the Star Wars universe.",
    "I was underwhelmed by the resolution of certain plot points in Episode 7.",
    "The chemistry between the characters in Star Wars Episode 7 was excellent.",
    "I couldn't get past the similarities between Episode 7 and A New Hope.",
    "The practical effects in Star Wars Episode 7 added authenticity to the film.",
    "I found the pacing in Episode 7 to be a bit slow in the middle.",
    "The nostalgia factor in Star Wars Episode 7 made it a memorable experience.",
    "I thought Episode 7 did a great job setting up the next installment in the trilogy.",
    "The character development in Star Wars Episode 7 was lacking for some characters.",
    "I enjoyed the fresh take on the Star Wars universe in Episode 7.",
    "The humor in Episode 7 felt forced and out of place at times.",
    "I was pleasantly surprised by the twists and turns in Star Wars Episode 7.",
    "The special effects in Episode 7 were groundbreaking and visually stunning.",
    "I found the dialogue in Star Wars Episode 7 to be cringe-worthy at times.",
    "The return of Han Solo added emotional weight to Episode 7.",
    "I thought the new droid, BB-8, was a highlight of Star Wars Episode 7.",
    "The plot of Episode 7 was too similar to previous Star Wars films for my liking.",
    "The political aspects introduced in Star Wars Episode 7 were confusing and unnecessary.",
    "I appreciated the strong female characters in Episode 7.",
    "I couldn't get enough of the lightsaber battles in Star Wars Episode 7.",
    "The plot twists in Episode 7 were predictable and lacked impact.",
    "I found Star Wars Episode 7 to be a worthy addition to the franchise.",
    "The cinematography in Episode 7 was breathtaking, capturing the essence of Star Wars.",
    "I didn't care for the new characters introduced in Star Wars Episode 7.",
    "The humor in Episode 7 felt forced and detracted from the serious tone of the story.",
    "I was disappointed by the lack of character development for certain key characters in Episode 7.",
    "The visual effects in Star Wars Episode 7 were revolutionary, pushing the boundaries of filmmaking.",
    "The pacing in Episode 7 was perfect, keeping me engaged from start to finish.",
    "I felt emotionally invested in the characters of Star Wars Episode 7.",
    "I found the plot of Episode 7 to be too derivative of the original trilogy.",
    "The soundtrack of Star Wars Episode 7 added to the emotional impact of the scenes.",
    "I thought the climax of Episode 7 was intense and satisfying.",
    "I didn't find the new villains in Star Wars Episode 7 to be as menacing as the originals.",
    "The world-building in Episode 7 expanded the Star Wars universe in exciting ways.",
    "I found the dialogue in Star Wars Episode 7 to be witty and well-written.",
    "The pacing of Episode 7 felt uneven, with some parts dragging on for too long.",
    "I was impressed by the performances of the cast in Star Wars Episode 7.",
    "I thought Episode 7 struck a good balance between honoring the past and paving the way for the future.",
    "The character arcs in Star Wars Episode 7 were well-executed and satisfying.",
    "I found the plot of Episode 7 to be too formulaic and predictable.",
    "The nostalgia factor in Star Wars Episode 7 made it a truly enjoyable experience.",
    "I didn't connect with the new characters in Episode 7 as much as I did with the original trilogy characters.",
    "The visual effects in Episode 7 were a visual feast, showcasing the advancements in technology.",
    "I thought Star Wars Episode 7 successfully captured the spirit of the original trilogy.",
    "The climax of Episode 7 left me on the edge of my seat, eagerly anticipating the next installment.",
    "I was let down by the lack of explanation for certain plot points in Star Wars Episode 7.",
    "The introduction of new Force powers in Episode 7 added an exciting dimension to the story.",
    "I thought the pacing in Star Wars Episode 7 was well-balanced, with a mix of action and character moments.",
    "I found the plot twists in Episode 7 to be surprising and kept me engaged throughout.",
    "The emotional depth in Star Wars Episode 7 resonated with me, making it a memorable experience.",
    "I didn't find the humor in Episode 7 to be as effective as in the original trilogy.",
    "The character dynamics in Episode 7 were well-developed and added depth to the story.",
    "I thought Star Wars Episode 7 successfully set the stage for the next chapter in the saga.",
    "The visual effects in Episode 7 were groundbreaking, pushing the boundaries of what is possible in filmmaking.",
    "I felt that the plot of Episode 7 relied too heavily on nostalgia and callbacks to the original trilogy.",
    "The introduction of new planets and locations in Star Wars Episode 7 added richness to the universe.",
    "I found the climax of Episode 7 to be emotionally satisfying and a fitting conclusion.",
    "The character development in Episode 7 was lacking for some of the new characters.",
    "The movie is pretty good if you compare the next ones"
]
star_wars_opinions = star_wars_opinions[:16]